#pragma once
#include <DXGInfrastructure/DXGInfrastructure.h>
#include <Device/D3D12Device.h>
#include <CommandQueue/D3D12CommandQueue.h>
#include <SwapChain/DXGISwapChain.h>
#include <Resources/Descriptors/RTV/D3D12RenderTargetView.h>
#include <CommandContext/D3D12CommandContext.h>
#include <Synchronizer/D3D12Synchronizer.h>
#include <RootSignature/D3D12RootSignature.h>
#include <Resources/Buffers/Vertex/D3D12VertexBuffer.h>
#include <PipelineState/D3D12PipelineState.h>
#include <Resources/Buffers/Constant/D3D12ConstantBuffer.h>
#include <Resources/Buffers/Index/D3D12IndexBuffer.h>
#include <Resources/Descriptors/DSV/D3D12DepthStencilView.h>
#include <Resources/Texture/Texture2D.h>
#include <Resources/Descriptors/SRV/D3D12ShaderResourceView.h>
#include <Structures/TwoDXStructs.h>